package at.fhv.itb5c.view.team.invite;

import javafx.fxml.FXML;
import java.rmi.RemoteException;
import org.controlsfx.control.CheckListView;
import at.fhv.itb5c.commons.dto.rmi.ITeamRMI;
import at.fhv.itb5c.commons.dto.rmi.ITournamentRMI;
import at.fhv.itb5c.commons.dto.rmi.IUserRMI;
import at.fhv.itb5c.logging.ILogger;
import at.fhv.itb5c.view.util.popup.ErrorPopUp;
import javafx.event.ActionEvent;
import javafx.scene.control.Label;

public class InvitePlayersToTournamentController implements ILogger{
	@FXML private Label _tournamentLabel;
	@FXML private Label _teamLabel;
	@FXML private CheckListView<IUserRMI> _teamMemberCheckListView;

	private InvitePlayerToTeamModel _model;
	
	public InvitePlayersToTournamentController(ITournamentRMI tournament, ITeamRMI team) {
		_model = new InvitePlayerToTeamModel(team, tournament);
		try {
			_tournamentLabel.setText(_model.getTournament().getName());
			_teamLabel.setText(_model.getTeam().getName());
		} catch (RemoteException e) {
			log.error(e.getMessage());
			ErrorPopUp.connectionError();
		}
	}
	
	@FXML
	public void _onActionCancleEventHandler(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void _acceptButtonOnActionEventHandler(ActionEvent event) {
		// TODO Autogenerated
	}
}
