package at.fhv.itb5c.view.tournament;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.io.IOException;

import at.fhv.itb5c.commons.dto.rmi.IMatchRMI;
import at.fhv.itb5c.logging.ILogger;
import at.fhv.itb5c.view.department.DepartmentViewFactory;
import at.fhv.itb5c.view.util.interfaces.IPanelClosable;
import at.fhv.itb5c.view.util.interfaces.IPanelCloseHandler;
import at.fhv.itb5c.view.util.popup.ErrorPopUp;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class MatchAddResultController implements IPanelClosable, ILogger {
	@FXML
	private Label _teamOneLabel;
	@FXML
	private Label _teamTwoLabel;
	@FXML
	private TextField _teamOneInput;
	@FXML
	private TextField _teamTwoInput;
	@FXML
	private Button _saveButton;
	@FXML
	private Button _cancelButton;
	IMatchRMI _match;

	public MatchAddResultController(IMatchRMI match) {
		_match = match;
	}
	
	// Event Listener on Button[#_saveButton].onAction
	@FXML
	public void saveButtonAction(ActionEvent event) {
		// TODO Autogenerated
	}
	
	// Event Listener on Button[#_cancelButton].onAction
	@FXML
	public void cancelButtonAction(ActionEvent event) {
		try {
			_panelCloseHandler.closeNext(new MatchViewFactory());
		} catch (IOException e) {
			log.error(e.getMessage());
			ErrorPopUp.criticalSystemError();
		}
	}
	
	private IPanelCloseHandler _panelCloseHandler;

	@Override
	public void setPanelCloseHandler(IPanelCloseHandler panelCloseHandler) {
		_panelCloseHandler = panelCloseHandler;
	}
}
